### ISSUE TITLE
File not found compiler error

### ISSUE THREAD

**Issue by matthiasbeyer** [IceBear2k/latex-template-hfu-cs#1]
```
LaTeX Error: File `img/Logo_HFU_rz_4c' not found.
```

**Comment by IceBear2k** [comment]
As stated in the readme file (https://github.com/IceBear2k/latex-template-hfu-cs/blob/master/README.md): "HFU logo in EPS format ("Logo_HFU_rz_4c.eps") is not provided due to licensing and needs to be downloaded separately into /img from http://marke.hs-furtwangen.de/ (requires login)."

**Comment by matthiasbeyer** [comment]
thx.
